In [1]:
l1=[1,2,3,4,5]
l2=[3,4,7,8,9]
r=l1+l2
print(r)


[1, 2, 3, 4, 5, 3, 4, 7, 8, 9]


In [2]:
import numpy as np
a=np.array(l1)
b=np.array(l2)
add=a+b
print(add)

[ 4  6 10 12 14]


In [3]:
l1=[[1,2,3,4,5],
[3,4,7,8,9],
[3,7,9,2,5]]
l2=[[2,4,5,9,1],
[4,6,7,8,2],
[3,9,1,4,9]]
import numpy as np
a=np.array(l1)
b=np.array(l2)
add=a+b
print(add)

[[ 3  6  8 13  6]
 [ 7 10 14 16 11]
 [ 6 16 10  6 14]]


In [4]:
print("Type of list1:", type(l1))
print("Type of array1:", type(a))


Type of list1: <class 'list'>
Type of array1: <class 'numpy.ndarray'>


In [5]:
import numpy as np
a=np.array(l1)
b=np.array(l2)
mul=a*b
print(mul)

[[ 2  8 15 36  5]
 [12 24 49 64 18]
 [ 9 63  9  8 45]]


In [6]:
divide = a / b
print(divide)


[[0.5        0.5        0.6        0.44444444 5.        ]
 [0.75       0.66666667 1.         1.         4.5       ]
 [1.         0.77777778 9.         0.5        0.55555556]]


In [7]:
sin_values = np.sin(a)
log_values = np.log(a)
log2_values = np.log2(a)
exp_values = np.exp(a)
print("Sin values:", sin_values)
print("Log values:", log_values)
print("Log2 values:", log2_values)
print("Exponential values:", exp_values)

Sin values: [[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
 [ 0.14112001 -0.7568025   0.6569866   0.98935825  0.41211849]
 [ 0.14112001  0.6569866   0.41211849  0.90929743 -0.95892427]]
Log values: [[0.         0.69314718 1.09861229 1.38629436 1.60943791]
 [1.09861229 1.38629436 1.94591015 2.07944154 2.19722458]
 [1.09861229 1.94591015 2.19722458 0.69314718 1.60943791]]
Log2 values: [[0.         1.         1.5849625  2.         2.32192809]
 [1.5849625  2.         2.80735492 3.         3.169925  ]
 [1.5849625  2.80735492 3.169925   1.         2.32192809]]
Exponential values: [[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
  1.48413159e+02]
 [2.00855369e+01 5.45981500e+01 1.09663316e+03 2.98095799e+03
  8.10308393e+03]
 [2.00855369e+01 1.09663316e+03 8.10308393e+03 7.38905610e+00
  1.48413159e+02]]
